name: CI for Pull Requests

on:
  pull_request:

jobs:
  prebuild:
    name: Prebuild Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64]
    timeout-minutes: 30
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- --strip --all --arch ${{ matrix.arch }}
